version: "3.4"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
#    volumes:
#      - grafana-volume:/var/lib/grafana

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    env_file:
      - .env
    environment:
      - bla=12
#    volumes:
#      - influxdb-volume:/var/lib/influxdb

networks:
  monitoring:
    driver: bridge

#volumes:
#  grafana-volume:
#    external: true
#  influxdb-volume:
#    external: true