{
 "title": "Operation Statistics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "thing",
    "label": "Thing",
    "query": "SELECT \"thing\", * FROM spindle_load"
   },
   {
    "name": "component",
    "label": "component",
    "query": "SELECT \"component\", * FROM componentload"
   }
  ]
 },
 "panels": [
  {
   "title": "Load Distribution C11",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 0 },
   "format": "h",
   "valueName": "total",
   "targets": [
    {
     "alias": "Power$tag_level",
     "groupBy": [
      { "params": [ "level" ], "type": "tag" }
     ],
     "measurement": "machinedata",
     "query": "SELECT sum(\"duration\") FROM \"componentload\" WHERE (\"thing\" = 'R0815') AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "thing", "operator": "=~", "value": "/^$thing$/" },
      { "condition": "AND", "key": "quantity", "operator": "=", "value": "powerC11" }
     ]
    }
   ]
  },
  {
   "title": "Load Distribution C12",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 0 },
   "format": "h",
   "valueName": "total",
   "targets": [
    {
     "alias": "Power$tag_level",
     "groupBy": [
      { "params": [ "level" ], "type": "tag" }
     ],
     "measurement": "machinedata",
     "query": "SELECT sum(\"duration\") FROM \"componentload\" WHERE (\"thing\" = 'R0815') AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "thing", "operator": "=~", "value": "/^$thing$/" },
      { "condition": "AND", "key": "quantity", "operator": "=", "value": "powerC12" }
     ]
    }
   ]
  },
  {
   "title": "Load Distribution C13",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 7, "x": 14, "y": 0 },
   "format": "h",
   "valueName": "total",
   "targets": [
    {
     "alias": "Power$tag_level",
     "groupBy": [
      { "params": [ "level" ], "type": "tag" }
     ],
     "measurement": "machinedata",
     "query": "SELECT sum(\"duration\") FROM \"componentload\" WHERE (\"thing\" = 'R0815') AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "thing", "operator": "=~", "value": "/^$thing$/" },
      { "condition": "AND", "key": "quantity", "operator": "=", "value": "powerC13" }
     ]
    }
   ]
  },
  {
   "title": "ED 40% Power Limit C11",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "machinedata",
     "query": "SELECT sum(\"duration\") FROM \"componentload\" WHERE (\"thing\" = 'R0815') AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       { "params": [ " / 200" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "thing", "operator": "=~", "value": "/^$thing$/" },
      { "condition": "AND", "key": "quantity", "operator": "=", "value": "powerC11" }
     ]
    }
   ]
  },
  {
   "title": "ED 40% C11",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "machinedata",
     "query": "SELECT sum(\"duration\")  / 6 FROM \"machinedata\" WHERE (\"thing\" =~ /^$thing$/ AND \"level\" = ' 80% ... 100%' AND \"quantity\" = 'powerC11') AND $timeFilter AND time <= now()",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "thing", "operator": "=~", "value": "/^$thing$/" },
      { "condition": "AND", "key": "level", "operator": "=", "value": " 80% ... 100%" },
      { "condition": "AND", "key": "quantity", "operator": "=", "value": "powerC11" }
     ]
    }
   ]
  },
  {
   "title": "ED 40% Power Limit C12",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "machinedata",
     "query": "SELECT sum(\"duration\") FROM \"componentload\" WHERE (\"thing\" = 'R0815') AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       { "params": [ " / 200" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "thing", "operator": "=~", "value": "/^$thing$/" },
      { "condition": "AND", "key": "quantity", "operator": "=", "value": "powerC12" }
     ]
    }
   ]
  },
  {
   "title": "ED 40% C12",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "machinedata",
     "query": "SELECT sum(\"duration\")  / 6 FROM \"machinedata\" WHERE (\"thing\" =~ /^$thing$/ AND \"level\" = ' 80% ... 100%' AND \"quantity\" = 'powerC12') AND $timeFilter AND time <= now()",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "thing", "operator": "=~", "value": "/^$thing$/" },
      { "condition": "AND", "key": "level", "operator": "=", "value": " 80% ... 100%" },
      { "condition": "AND", "key": "quantity", "operator": "=", "value": "powerC12" }
     ]
    }
   ]
  },
  {
   "title": "ED 40% Power Limit C13",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "machinedata",
     "query": "SELECT sum(\"duration\") FROM \"componentload\" WHERE (\"thing\" = 'R0815') AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       { "params": [ " / 200" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "thing", "operator": "=~", "value": "/^$thing$/" },
      { "condition": "AND", "key": "quantity", "operator": "=", "value": "powerC13" }
     ]
    }
   ]
  },
  {
   "title": "ED 40% C13",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "machinedata",
     "query": "SELECT sum(\"duration\")  / 6 FROM \"machinedata\" WHERE (\"thing\" =~ /^$thing$/ AND \"level\" = ' 80% ... 100%' AND \"quantity\" = 'powerC13') AND $timeFilter AND time <= now()",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "thing", "operator": "=~", "value": "/^$thing$/" },
      { "condition": "AND", "key": "level", "operator": "=", "value": " 80% ... 100%" },
      { "condition": "AND", "key": "quantity", "operator": "=", "value": "powerC13" }
     ]
    }
   ]
  }
 ]
}